FROM oven/bun:1
RUN apt-get update -y && apt-get install -y openssl

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./apps/backend/package.json ./apps/backend/package.json

RUN bun install
COPY ./apps/backend ./apps/backend

RUN bun run db:generate

EXPOSE 3001

CMD [ "bun","run","start:backend" ]
