FROM oven/bun:1
RUN apt-get update -y && apt-get install -y openssl
WORKDIR /usr/src/app

ARG DATABASE_URL

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/web/package.json ./apps/web/package.json
RUN bun install

COPY ./apps/web ./apps/web
RUN bun run db:generate
RUN export DATABASE_URL=$DATABASE_URL && bun run build

EXPOSE 3000

CMD [ "bun","run","start:web" ]