name: Deploy the backend
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v2
      # - name: Docker Login
      #   uses: docker/login-action@v2
      #   with:
      #     username: whispernet
      #     password: ${{secrets.DOCKER_ACCESS_TOKEN}}
      # - name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     file: ./docker/Dockerfile.backend
      #     push: true
      #     tags: whispernet/monolithic-backend
      - name: Deploy to backend
        uses: appleboy/ssh-action@v1
        with:
          host: 65.2.171.36
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker stop backend || true
            sudo docker run --name backend -e DATABASE_URL=${{secrets.DATABASE_URL}} -p 3001:3001 whispernet/monolithic-backend
